numero = int(input("Digite um número:"))
tabuada0 = int(numero * 0)
tabuada1 = int(numero * 1)
tabuada2 = int(numero * 2)
tabuada3 = int(numero * 3)
tabuada4 = int(numero * 4)
tabuada5 = int(numero * 5)
tabuada6 = int(numero * 6)
tabuada7 = int(numero * 7)
tabuada8 = int(numero * 8)
tabuada9 = int(numero * 9)
tabuada10 = int(numero * 10)
print("{} * 0 {}".format(numero,tabuada0))
print("{} * 1 {}".format(numero,tabuada1))
print("{} * 2 {}".format(numero,tabuada2))
print("{} * 3 {}".format(numero,tabuada3))
print("{} * 4 {}".format(numero,tabuada4))
print("{} * 5 {}".format(numero,tabuada5))
print("{} * 6 {}".format(numero,tabuada6))
print("{} * 7 {}".format(numero,tabuada7))
print("{} * 8 {}".format(numero,tabuada8))
print("{} * 9 {}".format(numero,tabuada9))
print("{} * 10 {}".format(numero,tabuada10))