numero = int(input("Digite um número:"))
dobro = (numero * 2)
triplo = (numero * 3)
raiz_quadrada = (numero ** (1/2))
print("O número é : {} e seu dobro é : {}".format(numero, dobro))
print("seu triplo : {} e sua raiz quadrada : {:.2f} ".format(triplo, raiz_quadrada))
