largura = int(input("Digite a Largura da parede:"))
altura = int(input("Digite a Altura da parede:"))
area = (largura * altura)
tinta = (area / 2)
print("Sua parede tem a dimensão de {}m x {}m  e sua área é de {}m².".format(largura,altura,area))
print("A quantidade de tinta necessária para pintar a parede é de : {} litros de tinta".format(tinta))